name: Build Code

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm install --no-save

      - name: run build
        run: npm run build

      - name: run inlang machine translate
        run: npx @inlang/cli@latest machine translate --force
